### PR TITLE
Update/about page

### PR DESCRIPTION
**Pull request by losndu**

### CODE REVIEW

**Comment by iankressin** [comment]
Code looks good, but we there's no point in having the hero section from the LP being part of the layout, otherwise it'll show in every page

**Review by iankressin — CHANGES_REQUESTED** [review]
Code looks good, but we there's no point in having the hero section from the LP being part of the layout, otherwise it'll show in every page

**Comment by 2077collective** [comment]
> Code looks good, but we there's no point in having the hero section from the LP being part of the layout, otherwise it'll show in every page

That's the Header component according to the design file

**Comment by losndu** [comment]
> Code looks good, but we there's no point in having the hero section from the LP being part of the layout, otherwise it'll show in every page

That's the Header component, checkout the source design file

**Pull request merged**
